name: Build

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [master, develop]

permissions:
  contents: read

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: tj-actions/changed-files@v47
        id: cf
      - run: npm install -g markdownlint-cli
      - run: echo "::add-matcher::.github/matchers/markdownlint.json"
      - run: markdownlint CHANGELOG.md
        if: contains(steps.cf.outputs.all_changed_files, 'CHANGELOG')
      - run: markdownlint README.md
        if: always() && contains(steps.cf.outputs.all_changed_files, 'README')

  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install shellcheck
        run: >-
          sc=shellcheck archive=$sc-stable.linux.x86_64.tar.xz
          dlpath="https://github.com/koalaman/${sc}/releases/download/stable"

          echo "::add-matcher::.github/matchers/shellcheck.json";
          curl -L "${dlpath}/${archive}" -o ./sc.tar.xz && tar -xf $_ &&
          mv -v ./{${sc}-stable/,}$sc && echo "${sc^} $(./$sc -V | grep ^ver)"
      - run: make
      - run: ./shellcheck -P src -f gcc release src/*.bash
        if: always()
