name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  release-tagged:
    name: Build release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Build Nextshot
        run: make
      - name: Generate Changelog
        run: >-
          TAG="${GITHUB_REF_NAME//./\.}";
          echo "Generating changelog for ${TAG}..."

          sed -n "/^## \[${TAG/v/}\]/,/^## \[/{//b;p}" CHANGELOG.md
          | tail -n+2 > ${{ github.workspace }}-changes.md

          cat ${{ github.workspace }}-changes.md
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: ${{ github.workspace }}-changes.md
          files: nextshot
